/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || "{CAB9ABF2-B2C5-4958-8C31-50AF3C490933}",
config.sitecoreApiHost = process.env.SITECORE_API_HOST || "https://sc1030xp1cd.local",
config.jssAppName = process.env.JSS_APP_NAME || "nextjs",
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || "/sitecore/api/graph/edge",
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || "en",
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || `${config.sitecoreApiHost}${config.graphQLEndpointPath}`;
module.exports = config;